# Generated by Django 5.1.1 on 2024-09-04 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulltimes',
            name='id_U',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.appuser'),
        ),
    ]
