# Generated by Django 5.1.1 on 2024-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='accessdate',
            new_name='accesstime',
        ),
        migrations.RenameField(
            model_name='fulltimes',
            old_name='accessdate',
            new_name='fulltime',
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='doctorname', max_length=255),
            preserve_default=False,
        ),
    ]
