# Generated by Django 5.1 on 2024-09-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_name_alter_doctor_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='career',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
