# Generated by Django 5.1.1 on 2024-09-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_accessdate_doctor_accesstime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='accesstime',
            new_name='accessdate',
        ),
    ]
