# Generated by Django 5.1.1 on 2024-09-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_career_alter_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulltimes',
            name='paid',
        ),
    ]
