# Generated by Django 5.1.1 on 2024-09-17 07:30

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=16),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
