# Generated by Django 5.1.1 on 2024-09-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appuser_otp_secret_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(default='nothing@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
