# Generated by Django 5.1 on 2024-09-11 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulltimes',
            name='paid',
        ),
    ]
