# Generated by Django 5.1 on 2024-09-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_fulltimes_paid'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltimes',
            name='id_D',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='fulltimes',
            name='id_U',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.appuser'),
        ),
    ]
