# Generated by Django 5.1.1 on 2024-09-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_fulltimes_id_d_alter_fulltimes_id_u'),
        ('doctor', '0004_rename_accesstime_doctor_accessdate'),
    ]

    operations = [
    ]
